JuliaDatabases/MySQL.jl

src/api.jl
src/datetime.jl
src/handy.jl
src/results.jl
src/types.jl

Fixes for deprecation warnings. Repaced String with AbstractString and Nothing with Void.

Fix Base.Nothing and Base.String deprecation warnings

---

src/datetime.jl
test/test_basic.jl
test/test_common.jl
test/test_prep.jl

Have `@test` assertions to check whether returned Array/DataFrame equal an expected result. Added `==` methods for date/time types.

Assert output equals expected result array/dataframe in test files

---

src/datetime.jl
src/results.jl

Hi
I noted that we call the function mysql_get_julia_type(mysqlfield_types[i]) for each row which is processed.
Is that truly necessary? It seems that the type of the columns should be constant in any MySQLDB.
I made some minor changes to reflect this. 
In the tests I made, this code ran **considerably faster (by a factor 2 or so)** than the current master.
Can you please take a look?
Also, I was hoping to increase performance by using multiple dispatch instead of if queries.
I am not sure at all whether I did everything right with regards to Time and Date formats.
Unfortunately I could not perform any tests, as I do not have that DB which the tests require.
Thank you.
Bernhard

Suggestion for peformance improvement

---

README.md
src/MySQL.jl
src/results.jl
src/types.jl
test/Benchmarks/benchmark.jl
test/Benchmarks/create_datasets.jl
test/test_basic.jl
test/test_prep.jl

1) Removed unused `mysqlfield_types` array in `populate_row!()`.
2) Update readme and test/Benchmarks for removal of `mysql_execute_multi_query()`.
3) Incorporate #22 to `mysql_get_row_as_vector!()` and related functions.
4) Some cosmetic changes to remove tabs.

Changes for cleanup, update and performance.

---

src/api.jl
src/handy.jl

* `mysql_connect` now takes an optional parameter `opts` which is a Dictionary of `option => value`.
* This lets the user set multiple options before connecting.

Provide a way to set options before connecting

---

src/api.jl
src/handy.jl

Added wrapper to `mysql_insert_id()`.  Returns the last insert's auto increment id.

Added mysql_insert_id()

---

src/handy.jl

Call `mysql_error` when `mysql_real_connect` fails so that the reason for connection failure is known.

Report `mysql_error` when `mysql_real_connect` fails

---

README.md
src/handy.jl
src/iterators.jl
src/results.jl
src/types.jl
test/test_prep.jl

Have `mysql_stmt_init` be called as part of `mysql_connect` and `mysql_stmt_close` as part of `mysql_disconnect`.

Remove the need to call `mysql_stmt_init` and `mysql_stmt_close`

---

REQUIRE
test/runtests.jl
test/server.ini
test/test_common.jl

Put test server configuration in a `.ini` file.

Pick up server config from .ini file in tests

---

src/api.jl
src/consts.jl
src/handy.jl

Added two new optional parameters to mysql_connect :
- port
- socket
New parameters allow connection using a not standard port ( 3306 ) or a not default socket ( i.e. (/var/mysql/mysql.sock )
Examples:
```
julia> conn2 = mysql_connect("127.0.0.1", "support", "support", "", port=3307)
MySQL Handle
------------
Host: 127.0.0.1
User: support
DB:
```
```
julia> conn3 = mysql_connect("localhost", "support", "support", "", socket="/tmp/mysql-3307.sock")
MySQL Handle
------------
Host: localhost
User: support
DB:
```

Enhanced connection

---

src/handy.jl
src/types.jl

Fix method overwrite warning for `MySQLResult` constructor.

Fix method overwrite warning

---

README.md
src/config.jl

[Percona](https://www.percona.com) provides a popular 100% interoperable build of mysql for high performance situations; this PR just adds that to the list of possible libs to hunt for in addition to clarifying the troubleshooting steps in the README that I felt were unclear.

Better troubleshooting docs; add support for percona libraries on OSX

---

src/handy.jl
test/test_basic.jl
test/test_prep.jl

Address #84 
1) Always return `Vector{X}` when user requests output format as X.
2) Wrap number of affected rows in requested type.

Make mysql_execute type stable

---

README.md

`('Sam', 35000.00, '2012-18-17)` In this statement, month is invalid and date is not enclosed in single quotes, hence when executed, this results in a syntax error, this PR fixes that issue.

Fixes a typo and a bug in the example

---

README.md
src/MySQL.jl
test/runtests.jl

Adds while loop to MySQL.execute! to enable multi-statement execution. This functionality is already enabled via the client_flag, but is not working (see [Issue 104](https://github.com/JuliaDatabases/MySQL.jl/issues/104)).
This implements the solution from the [MySQL C API docs](https://dev.mysql.com/doc/refman/8.0/en/c-api-multiple-queries.html), but assumes that only non-returning statements are being executed.  This is consistent with the current implementation and the docs.

enable multi-statement execute

---

src/prepare.jl
test/runtests.jl

The issue here is that we use unsigned int buffers underneath for
binding the prepared statement parameters, and we were doing a simple
assignment like: `buf[1] = x`. This kind of basic `setindex!` calls
convert, which calls something like `UInt64(-1)` and will throw
InexactErrors. But we don't want to conver the value to anything, we
just want the plain bits stored in our buffer, so the solution here is
pretty simple: cast the bits to the right type.

Fix #144: error when binding negative integers to prepared stmt

---

src/MySQL.jl
src/api/capi.jl
src/api/papi.jl
src/execute.jl
src/prepare.jl
test/runtests.jl

Fixes #149.
The issue here is that calling stored procedures that return resultsets
return the resultset, and then an extra, empty resultset (who knows why,
but whatever). In general, we weren't handling when queries returned
multiple resultsets anyway, so this was a more general problem. We now
will return the first resultset as the official resultset and clear out
any additional resultsets if they exist. We should definitely come up
with a better api if people actually need/want multiple resultsets, but
that's a problem for another day.
It turns out we also had problems returning resultsets from prepared
statements, which is the reason for the extra tests and code changes in
prepare.jl.

Fix calling stored procedures that return resultsets

---

src/MySQL.jl
src/execute.jl
test/runtests.jl

This allows returning multiple resultsets from a single query call; this
requires setting `multi_statements` to `true` by default, but I couldn't
think of any downside to doing this (vs. the alternative in which a user
finds the function, tries it and immediately fails and has to restart
their connection by setting the flag). Prepared statements don't support
multiple resultsets, and an error is thrown appropriately (from mysql
itself). This PR requires
https://github.com/JuliaDatabases/DBInterface.jl/pull/26 to be merged
and tagged first.

Implement new `DBInterface.executemultiple` interface function

---

src/MySQL.jl
test/runtests.jl

This PR fixes an issue with unsigned float columns.
Fixes #173

Don't call unsigned(T) for T <: AbstractFloat

---

src/api/apitypes.jl
test/runtests.jl

Fixes #175. As @david-macmahon pointed out, it was a bit strange that we
were special-casing the binding of MYSQL_TIME structs when converting
from DateTime. The mysql DATETIME type specifically supports dates
between 1000-01-01 to 9999-12-31 23:59:59, so there's no reason we
should be special-casing 1970-01-01.

Improve handing of DateTime values for 1970-01-01

---

src/MySQL.jl
src/api/API.jl
src/api/apitypes.jl
src/api/consts.jl
src/execute.jl
src/load.jl
src/prepare.jl
test/runtests.jl

Fixes #165 (and #172). So the proposal here is a bit tricky, but here's
what's going on in this PR:
* Introduce a new DateAndTime struct, which just contains separate
`Date` and `Time` fields, where the `time` field can support up to
Nanosecond precision
* For _prepared_ statement execution, we actually return a DateTime
column for > millisecond precision, and there used to be no warning.
We now emit a warning that precision is being lost and that
`mysql_date_and_time=true` should be passed to avoid such loss
* For _directly executed_ queries, we throw an InexactError and now
emit the same warning that `mysql_date_and_time=true` should be passed
to avoid such errors. We could perhaps match the prepare behavior and
return `DateTime`, but I wanted to avoid changing too much all at once
* …

Introduce a new DateAndTime sturct for > millisecond precision support

---

src/MySQL.jl
test/runtests.jl

Fixes #170. As far as I can tell, certain projects suggest/require using
"mysql://", "mysqlx://", "jdbc:mysql://", etc. as the protocol portion
of the host url. This ends up with really weird behavior in MySQL.jl
because it assumes there's a plugin that needs to be loaded. So the fix
here is just a simple check if "mysql://" is in the host url and if so,
only use the rest of the string after it.

Ignore any host url protocol that includes "mysql://"

---

src/MySQL.jl
src/api/capi.jl
test/my.ini
test/runtests.jl

Fixes #166. Wowza what an issue. After spending way too much time
googling various forms of "can't read password from mariadb options
file", I started poking around the capi.jl file, and reading anything
related to "options". I was trying to see if there was a way to have a
debug print of what options were actually read from an options file.
That's when I found the following in the docs for `mysql_real_connect`,
which I'm now very thankful that past me decided to copy/paste all the
api docs for every single api function.
```
For passwd, specify a value of NULL. (For the password, a value of the empty string in the mysql_real_connect() call cannot be overridden in an option file, because the empty string indicates explicitly that the MySQL account must have an empty password.)
```
So if …

Ensure passwords can be read from options files

---

src/MySQL.jl
src/load.jl
src/prepare.jl
test/runtests.jl

Fixes https://github.com/JuliaDatabases/MySQL.jl/issues/194.
Basically just a typo in the core 1-byte loading code. We probably started out with treating `Bool` separately from Int8/UInt8 and then combined the code support, but forgot to change the bitcast to `UInt8` instead of `Bool`, which resulted in the "truncation" result shared in the original issue.

Fix issue loading Int8/UInt8 values into mysql table

---

.gitignore
Project.toml
src/load.jl
test/runtests.jl

`transaction()` used to just turn off autocommit, which means that rollback doesn't work:
```julia
julia> transaction(db) do
stmt = prepare(db, "insert into foo (a) values (?);")
execute(stmt, [6])
error("force rollback")
end
ERROR: force rollback
Stacktrace:
[1] error(s::String)
@ Base ./error.jl:35
[2] (::var"#1#2")()
@ Main ./REPL[6]:4
[3] transaction(f::var"#1#2", ::MySQL.Connection)
@ DBInterface ~/.julia/packages/DBInterface/1Gmxx/src/DBInterface.jl:166
[4] top-level scope
@ REPL[6]:1
julia> DataFrame(execute(db, "select * from foo"))
6×1 DataFrame
Row │ a      
│ Int32? 
─────┼────────
1 │      1
2 │      1
3 │      1
4 │      2
5 │      1
6 │      6
```
I didn't find any C API for starting a transaction, so I am using the SQL instead. ref. …

Fix transaction() not actually using a transaction

---

src/api/capi.jl
src/api/ccalls.jl

Hello,
This litte PR to avoid the anoying error "Method overwriting ..." error each time you want to use the module
Not very clean but very low footprint and should not break anything.
For beta tester, you could use my repo in place of the official : https://github.com/pascalr0410/MySQL.jl.git
Regards,
Pascal.

Escaping the error "Method overwriting is not permitted during Module precompilation" with Julia V 1.10

---

Project.toml

Simply trying to remove the restricting compat.
Please let me know what the original reason for this quite restrictive compat has been. I am sure there is actually a good reason.
Resolves #221

Compat Upgrade of MariaDB_Connector_C_jll
